

l9:
  games:
    EMERALD_ISLE:
      path: level9/SNA/V2/EMERALD.SNA
      archive: level9.zip
      folder: level9
    WORM_PC:
      path: worm-pc/WORM.DAT
      pic: worm-pc/WORM.CGA
      archive: worm-pc.zip
      folder: worm-pc